version: '3.8'

services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data
      # マイグレーションが必要な場合はコメント解除
      # - ./pb_migrations:/pb/pb_migrations
      # カスタムフックが必要な場合はコメント解除
      # - ./pb_hooks:/pb/pb_hooks
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  pb_data:
    driver: local
